### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by rklass** [RPi-Distro/vlc#104]
If we play an mp4 over network using PI3 bulley Versionn, it takes some minutes and then the PI is stopping to work (CPU usage for VLC is 100%....). Omxplayer is running the same mp4 without any problems.
Iststarts well, but after ab. 10 min the PI is stopping to wor and showing in top:  MEM 100%  CPU 100% for running vlc.

**Comment by jc-kynesim** [comment]
Can you give me a copy of the mp3 please? Or are you suggesting that all mp3s are broken?

**Comment by rklass** [comment]
Sorry, I had to change the content. It is valid for mp4 files coming over network.

**Comment by jc-kynesim** [comment]
Well same question then - Can you give me a copy of the mp4 please? Or are you suggesting that all mp4s are broken? If you are saying that all mp4s are broken can you give me the command line you are using please (over the network could mean quite a lot of things)? or if not command line then menu items and what you clicked/typed.

**Comment by rklass** [comment]
We can close this ticket. In the lateat version of vlc in Raspian Bullseye it is running in a PI3. 
Thanks to those who solved it.

**Comment by rklass** [comment]
THANKS
