### ISSUE TITLE
SRT support

### ISSUE THREAD

**Issue by its27** [RPi-Distro/vlc#11]
Hi,

I have been testing the latest VLC release on the RPI3 and it works great, the only problem is that it can't open SRT:// URLs while the same version in my desktop PC can.

Are you able to add the SRT plugin?

Many Thanks,

**Comment by jc-kynesim** [comment]
Can you give an example of something that doesn't work? At least in local playback .srt files give subtitles to a similarly named video file.

**Comment by its27** [comment]
Sure.

The issue is with the secure reliable transport protocol rather than SRT subtitles, please see the forum link below.

https://forum.videolan.org/viewtopic.php?t=143500

**Comment by its27** [comment]
https://www.srtalliance.org/srt-streams-vlc-3-0/

**Comment by jc-kynesim** [comment]
Ta for the links - the issue is that the VLC SRT module relies on an external SRT package that doesn't appear to exist for our version of Debian.

**Comment by scharette88** [comment]
Hey guys,

+1 here for SRT support in this VLC. Performance and latency of SRT on unstable network is really impressive, it would be a great feature to have it supported in this build,

Thanks all for all your hard work, it make the RPI a very powerful media player !

**Comment by XECDesign** [comment]
@jc-kynesim I can take a look at adding the package. Would you happen to have a link for it?

**Comment by llamafilm** [comment]
The code to support this is already in here. You just need to install libsrt and add —enable-srt when you build. But there are some issues, see #34.
