### ISSUE TITLE
RaspberryPiOS x86 VLC player menu bar and settings coruption issue

### ISSUE THREAD

**Issue by b1ack0p** [RPi-Distro/vlc#62]
Build : Linux  4.19.0-20-686-pae #1 SMP Debian 4.19.235-1 (2022-03-17) i686 GNU/Linux
VLC version: 3.0.12-0+deb10u1

VLC toolbar menu doesn't show up and they look corrupted as seen in screenshots below.

screenshots:

![Screenshot from 2022-04-14 23-50-16](https://user-images.githubusercontent.com/72235930/163475254-049f585f-e524-44d5-9c23-9028d3f24384.png)
![Screenshot from 2022-04-14 23-50-57](https://user-images.githubusercontent.com/72235930/163475263-30982112-3e89-4e3e-a83d-33450ff995fe.png)

**Comment by XECDesign** [comment]
A new, bullseye-based version of the .iso was released a few days ago. I'm not able to reproduce the problem on that release. Are you still seeing it?

**Comment by b1ack0p** [comment]
> A new, bullseye-based version of the .iso was released a few days ago. I'm not able to reproduce the problem on that release. Are you still seeing it?

hi. thank you for response. i tested RaspiOS x86/bullseye on virtualbox and menu bar on VLC player is visible. seems no more problem with VLC player on bullseye version. I will install it on real machine later.
