### ISSUE TITLE
VLC stops DPMS even after it's not longer running

### ISSUE THREAD

**Issue by notGMman** [RPi-Distro/vlc#75]
RPi4B, running 64-bit OS, upgraded using dist-upgrade on Mon 3rd October 2022.
Linux XXX 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

"xset dpms force off" works after booting. Various apps run to test and DPMS continues to work afterwards. VLC run and video played which stops DPMS whilst running, as expected, but when app stopped (and confirmed to be stopped with "ps") DPMS not longer works - screen briefly (sub 1s) blanks then returns.

HUGE apologies - close this. Not VLC - happens after playing a video in Chromium too. So I guess the Pi firmware isn't hearing "renable DPMS" messages.

**Comment by popcornmix** [comment]
Continues here: https://github.com/raspberrypi/linux/issues/5203
