### ISSUE TITLE
Any plans to port hw acceleration patches into 3.0.19? 

### ISSUE THREAD

**Issue by graysky2** [RPi-Distro/vlc#89]
I tried rebasing [mmal_35.patch](https://github.com/RPi-Distro/vlc/blob/bullseye-rpt/debian/patches/mmal_35.patch) for version 3.0.19 but met with tons of build errors.  This requires someone with more knowledge than I have.

[Here](https://gist.github.com/graysky2/5b5f99e2efd54e5f4578f4697d40a53d) are the hunks that got applied cleanly.
[Here](https://gist.github.com/graysky2/9b57050c8a51bf4f50fd0a3ad48b2f8f) is what I manually rebased.

[This](https://gist.github.com/graysky2/0135858dceff7c0348a340091864783d) is the resulting build log.

**Comment by jc-kynesim** [comment]
Short answer - yes. Indeed it is done - if you look at branch dev/3.0.19/port_1 in https://github.com/jc-kynesim/vlc.git - it has had very limited testing so far and there is some question about whether we want to track the version that debian uses or go forward to 3.0.19.

**Comment by graysky2** [comment]
Nice!  Is this correct?  I cloned your repo, then pulled in vlc upstream and generated the patch like this:
```
git remote add vlc-upstream https://code.videolan.org/videolan/vlc.git
git fetch vlc-upstream
git fetch --tags vlc-upstream
git checkout dev/3.0.19/port_1
git diff-index --binary 3.0.19 > 0003-dev-3.0.19-port_1.patch
```

I assume that is the new version of [mmal_35.patch](https://github.com/RPi-Distro/vlc/blob/bullseye-rpt/debian/patches/mmal_35.patch), yes?  Are the other patches in [debian/patches](https://github.com/RPi-Distro/vlc/tree/bullseye-rpt/debian/patches) meant to be applied on top of that?

When I do so I see [build errors](https://gist.github.com/graysky2/7a9f30c059249129d5a3a9fa0914555e).

**Comment by graysky2** [comment]
Nice!  For others finding this:
```
git remote add vlc-upstream https://code.videolan.org/videolan/vlc.git
git fetch vlc-upstream
git fetch --tags vlc-upstream
git checkout dev/3.0.19/port_1
git diff-index --binary 3.0.19 > 0003-dev-3.0.19-port_1.patch
```
Here are my build files: https://github.com/graysky2/PKGBUILDs/tree/vlc-rpi-3.0.19/alarm/vlc-rpi
